#pragma once

#ifndef VERSION
#define VERSION 1
#define CONFIG_VERSION 1
#endif

#ifndef SERIAL_CONNECTION_SPEED
#define SERIAL_CONNECTION_SPEED 115200
#endif

#ifndef DEFAULT_HTTP_SERVER_PORT
#define DEFAULT_HTTP_SERVER_PORT 80
#endif

#ifndef DEFAULT_MQTT_SERVER_HOST
#define DEFAULT_MQTT_SERVER_HOST "test.mosquitto.org"
#define DEFAULT_MQTT_CLIENT_ID "ardumi-test"
#define DEFAULT_MQTT_KEEPALIVE 15
#define DEFAULT_MQTT_TIMEOUT 30
#define DEFAULT_MQTT_CONNECTION_RETRIES 2
#endif